name: 'Lint'
description: 'Performs Linting every Helm Chart'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'
    
runs:
  using: node20
  main: ../../../../typescript/packages/helm-chart/linting/dist/index.js
